WITH CTE AS (
    select
    To_TIMESTAMP(STARTED_AT) AS STARTED_AT,
    DATE(To_TIMESTAMP(STARTED_AT)) AS DATE_STARTED_AT,
    HOUR(To_TIMESTAMP(STARTED_AT)) AS HOUR_STARTED_AT,

    CASE 
    WHEN DAYNAME(To_TIMESTAMP(STARTED_AT)) IN ('Sat','Sun') then 'WEEKEND'
    ELSE 'BUSINESS DAYS'
    END AS WEEK_TYPE,

    CASE WHEN MONTH(To_TIMESTAMP(STARTED_AT)) IN ('12','1','2') then 'WINTER'
    WHEN MONTH(To_TIMESTAMP(STARTED_AT)) IN ('3','4','5') then 'SUMMER'
    WHEN MONTH(To_TIMESTAMP(STARTED_AT)) IN ('6','7','8') then 'SPRING'
    ELSE 'AUTUMN' END AS SEASON

    from
    {{ source('DEMO', 'BIKE_TABLE') }}
    WHERE STARTED_AT!='started_at'
)

select * from CTE